--- 
common: 
  license_key: '<%= EY::Config.get("New Relic", 'license_key') %>'
  app_name: '<%= Rails.application.class.parent_name %>'
  monitor_mode: true
  developer_mode: false
  log_level: debug
  ssl: true
  apdex_t: 0.5
  capture_params: false
  transaction_tracer: &id001 
    enabled: true
    transaction_threshold: "2.0"
    record_sql: obfuscated
    stack_trace_threshold: 0.5
  error_collector: &id002 
    enabled: true
    capture_source: true
    ignore_errors: ActionController::RoutingError
  agent_enabled: true
  host: staging-collector.newrelic.com
development: 
  #license_key: d67afc830dab717fd163bfcb0b8b88423e9a1a3b
  #app_name: RubyTestApp_Autotest
  monitor_mode: true
  developer_mode: true
  log_level: info
  ssl: true
  apdex_t: 0.5
  capture_params: false
  transaction_tracer: *id001
  error_collector: *id002
  agent_enabled: true
  host: staging-collector.newrelic.com
test: 
  #license_key: d67afc830dab717fd163bfcb0b8b88423e9a1a3b
  #app_name: RubyTestApp_Autotest
  monitor_mode: false
  developer_mode: false
  log_level: info
  ssl: true
  apdex_t: 0.5
  capture_params: false
  transaction_tracer: *id001
  error_collector: *id002
  agent_enabled: true
  host: staging-collector.newrelic.com
production: 
  #license_key: d67afc830dab717fd163bfcb0b8b88423e9a1a3b
  #app_name: RubyTestApp_Autotest
  monitor_mode: true
  developer_mode: false
  log_level: info
  ssl: true
  verify_certificate: false
  apdex_t: 0.5
  capture_params: true
  transaction_tracer: *id001
  error_collector: *id002
  agent_enabled: true
  host: staging-collector.newrelic.com
  #proxy_host: localhost
  #proxy_port: 3128
  #proxy_user: qa
  #proxy_pass: 4maline
staging: 
  #license_key: d67afc830dab717fd163bfcb0b8b88423e9a1a3b
  #app_name: RubyTestApp_Autotest
  monitor_mode: true
  developer_mode: false
  log_level: info
  ssl: true
  apdex_t: 0.5
  capture_params: false
  transaction_tracer: *id001
  error_collector: *id002
  agent_enabled: true
  host: staging-collector.newrelic.com
